//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opd
    {
        public int OpdId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> TokenNo { get; set; }
        public string VisitType { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
