//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opd()
        {
            this.OpdDetails = new HashSet<OpdDetail>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int OpdId { get; set; }
        public int PatientId { get; set; }
        public string OpdNo { get; set; }
        public int TokenNo { get; set; }
        public System.DateTime OpdDate { get; set; }
        public byte OpdType { get; set; }
        public decimal LineTotal { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public decimal GrandTotal { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte BillStatus { get; set; }
        public byte PaymentStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<decimal> TotalDuesAmount { get; set; }
        public Nullable<decimal> TotalPaidAmount { get; set; }
        public string CancelReason { get; set; }
        public Nullable<System.DateTime> OpdCancelDate { get; set; }
        public Nullable<byte> OpdStatus { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpdDetail> OpdDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
