//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opd
    {
        public int OpdId { get; set; }
        public int PatientId { get; set; }
        public int OpdNo { get; set; }
        public int TokenNo { get; set; }
        public System.DateTime OpdDate { get; set; }
        public byte OpdType { get; set; }
        public decimal LineTotal { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public decimal GrandTotal { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int PaymentId { get; set; }
        public byte PaymentStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TotalQty { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
