//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpdDetail
    {
        public int OpdDetailId { get; set; }
        public int OpdId { get; set; }
        public int ServiceChargeId { get; set; }
        public decimal ServiceChargeAmount { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal Total { get; set; }
    }
}
