//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSubCategory
    {
        public int ServiceSubCategoryId { get; set; }
        public int ServiceCategoryId { get; set; }
        public string ServiceSubCategoryName { get; set; }
        public byte Status { get; set; }
    
        public virtual ServiceCategory ServiceCategory { get; set; }
    }
}
